apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scraper-dotnet
spec:
  endpoints:
    - interval: 30s
      port: telemetry
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      scraper: dotnet
